### ISSUE TITLE
求指导，数据库连不上

### ISSUE THREAD

**Issue by bestZwei** [netcccyun/dnsmgr#106]
![{1D81D572-C845-4E61-A504-DB9B1CA867BE}](https://github.com/user-attachments/assets/9f242fe4-94f5-4cc2-b69d-c8d0bbb35b3b)

![{55F684D5-331C-4492-B616-50B140E5D723}](https://github.com/user-attachments/assets/c546839b-add8-48d7-9a31-396b98b2dea3)

显示`{"code":0,"msg":"连接数据库失败：数据库地址填写错误！"}` 

我在1panel使用的 docker compose:

```
version: '3'
services:
  dnsmgr-web:
    container_name: dnsmgr-web
    stdin_open: true
    tty: true
    ports:
      - 8085:80
    volumes:
      - /volume1/docker/dnsmgr/web:/app/www
    image: netcccyun/dnsmgr
    environment:
      - DB_HOST=localhost # 1Panel-mysql-JDMB 也试过
      - DB_PORT=3306 
      - DB_USER=root1
      - DB_PASSWORD=12KJ3456 
      - DB_DATABASE=dnsmgr
    networks:
      - dnsmgr-network


networks:
  dnsmgr-network:
    driver: bridge
```
